# GitHub Pages configuration for a technical book

# Site settings
# (You can customize these as needed)
title: "CAP Chronicles: Part 1 – The Art of Building"
author: "Arun Jadhav"
description: "A technical book on SAP CAP, development, and the Bookshop sample."

# Use a supported GitHub Pages theme
# See https://pages.github.com/themes/
theme: minima

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
