# GitHub Pages configuration for a technical book

# Site settings
title: "CAP Chronicles"
longtitle: "CAP Chronicles: Part 1 – The Art of Building"
author: "Arun Jadhav"
author_email: "a2jadhav@gmail.com"
description: "A technical book on SAP CAP, development, and the Bookshop sample."

# Use jekyll-chapterbook theme via remote_theme
remote_theme: jasongrimes/jekyll-chapterbook

# Optional settings
baseurl_canonical: ""
favicon_path: assets/gitbook/images/favicon.ico

bookcrumbs:
  book_url: /book.html
  contents_url: /contents.html
  book_icon: assets/gitbook/images/apple-touch-icon-precomposed-152.png

sidebar_nav_top:
- label: CAP Chronicles Home
  url: /index.html
- label: Preface
  url: /Preface
- label: The Shift, The Struggle, The Spark
  url: /Chapter-1
- label: The First Real Build
  url: /Chapter-2
- label: The Setup (Immediate Destruction of Confidence)
  url: /Chapter-3
- label: The Service Layer
  url: /Chapter-4
- label: The Other Side of the Service
  url: /Chapter-5
- label: The Ping, The Pong, The Popcorn
  url: /Chapter-6
- label: The Window to the Bookshop — Fiori and Beyond
  url: /Chapter-7
- label: Beneath the Shelves — A Conversation About Databases
  url: /Chapter-8
- label: Taking the Bookshop to the World — Deployment Options
  url: /Chapter-9
- label: Beyond the Books — The Bigger Picture of CAP
  url: /Chapter-10

bottom_nav:
- label: Home
  url: /index.html
- label: Book
  url: /book.html

in_chapter_toc:
  enabled: true
  h_min: 2
  h_max: 3

sidebar_toc:
  enabled: false
  h_min: 2
  h_max: 3

github_edit:
  enabled: true
  base_url: https://github.com/arunjadhav/CAPM-Chronicles-Part-1-The-Art-of-Building/edit/main/

extra_css:

show_drafts_in_dev: false

parts:
  - title: "Contents"
    chapters:
      - title: "Preface"
        url: /Preface
      - title: "The Shift, The Struggle, The Spark"
        url: /Chapter-1
      - title: "The First Real Build"
        url: /Chapter-2
      - title: "The Setup (Immediate Destruction of Confidence)"
        url: /Chapter-3
      - title: "The Service Layer"
        url: /Chapter-4
      - title: "The Other Side of the Service"
        url: /Chapter-5
      - title: "The Ping, The Pong, The Popcorn"
        url: /Chapter-6
      - title: "The Window to the Bookshop — Fiori and Beyond"
        url: /Chapter-7
      - title: "Beneath the Shelves — A Conversation About Databases"
        url: /Chapter-8
      - title: "Taking the Bookshop to the World — Deployment Options"
        url: /Chapter-9
      - title: "Beyond the Books — The Bigger Picture of CAP"
        url: /Chapter-10

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _drafts
  - tmp

# Build settings
destination: ./_site
incremental: false
regenerate: true

# Plugins
plugins:
  - jekyll-readme-index

# Collections
collections:
  chapters:
    output: true
  pages:
    output: true
    permalink: /:slug:output_ext

# Defaults
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
syntax_highlighter_style: colorful
markdown_ext: markdown,mkdown,mkdn,mkd,md

page_width: 800px
