# GitHub Pages configuration for a technical book

# Site settings
title: "CAP Chronicles: Part 1 – The Art of Building"
author: "Arun Jadhav"
description: "A technical book on SAP CAP, development, and the Bookshop sample."

# Use jekyll-gitbook theme via remote_theme
github: [metadata]
remote_theme: sighingnow/jekyll-gitbook

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
